version: "2"

services:
  nats:
    image: "nats:latest"
    entrypoint: "/nats-server -js"
    expose:
      - "4222"
    ports:
      - "8221:8222"
    hostname: nats-server
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    links:
      - nats
    depends_on:
      - nats
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  git-client:
    build:
      context: "./"
      dockerfile: ./client.dockerfile
    links:
      - nats
    environment:
      - "NATS_ADDRESS=nats://nats:4222"
      - "NATS_TOKEN=UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD"
      - "DB_ADDRESS=127.0.0.1"
      - "DB_PORT=9000"
    depends_on:
      - nats
