{
 "title": "Git Webhook Events Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gitlab Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitlab Release Event",
     "type": "table",
     "description": "{\n  \"id\": 1,\n  \"created_at\": \"2020-11-02 12:55:12 UTC\",\n  \"description\": \"v1.1 has been released\",\n  \"name\": \"v1.1\",\n  \"released_at\": \"2020-11-02 12:55:12 UTC\",\n  \"tag\": \"v1.1\",\n  \"object_kind\": \"release\",\n  \"project\": {\n    \"id\": 2,\n    \"name\": \"release-webhook-example\",\n    \"description\": \"\",\n    \"web_url\": \"https://example.com/gitlab-org/release-webhook-example\",\n    \"avatar_url\": null,\n    \"git_ssh_url\": \"ssh://git@example.com/gitlab-org/release-webhook-example.git\",\n    \"git_http_url\": \"https://example.com/gitlab-org/release-webhook-example.git\",\n    \"namespace\": \"Gitlab\",\n    \"visibility_level\": 0,\n    \"path_with_namespace\": \"gitlab-org/release-webhook-example\",\n    \"default_branch\": \"master\",\n    \"ci_config_path\": null,\n    \"homepage\": \"https://example.com/gitlab-org/release-webhook-example\",\n    \"url\": \"ssh://git@example.com/gitlab-org/release-webhook-example.git\",\n    \"ssh_url\": \"ssh://git@example.com/gitlab-org/release-webhook-example.git\",\n    \"http_url\": \"https://example.com/gitlab-org/release-webhook-example.git\"\n  },\n  \"url\": \"https://example.com/gitlab-org/release-webhook-example/-/releases/v1.1\",\n  \"action\": \"create\",\n  \"assets\": {\n    \"count\": 5,\n    \"links\": [\n      {\n        \"id\": 1,\n        \"external\": true,\n        \"link_type\": \"other\",\n        \"name\": \"Changelog\",\n        \"url\": \"https://example.net/changelog\"\n      }\n    ],\n    \"sources\": [\n      {\n        \"format\": \"zip\",\n        \"url\": \"https://example.com/gitlab-org/release-webhook-example/-/archive/v1.1/release-webhook-example-v1.1.zip\"\n      },\n      {\n        \"format\": \"tar.gz\",\n        \"url\": \"https://example.com/gitlab-org/release-webhook-example/-/archive/v1.1/release-webhook-example-v1.1.tar.gz\"\n      },\n      {\n        \"format\": \"tar.bz2\",\n        \"url\": \"https://example.com/gitlab-org/release-webhook-example/-/archive/v1.1/release-webhook-example-v1.1.tar.bz2\"\n      },\n      {\n        \"format\": \"tar\",\n        \"url\": \"https://example.com/gitlab-org/release-webhook-example/-/archive/v1.1/release-webhook-example-v1.1.tar\"\n      }\n    ]\n  },\n  \"commit\": {\n    \"id\": \"ee0a3fb31ac16e11b9dbb596ad16d4af654d08f8\",\n    \"message\": \"Release v1.1\",\n    \"title\": \"Release v1.1\",\n    \"timestamp\": \"2020-10-31T14:58:32+11:00\",\n    \"url\": \"https://example.com/gitlab-org/release-webhook-example/-/commit/ee0a3fb31ac16e11b9dbb596ad16d4af654d08f8\",\n    \"author\": {\n      \"name\": \"Example User\",\n      \"email\": \"user@example.com\"\n    }\n  }\n}",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "select event.metrics.object_kind as Event,\r\nevent.metrics.created_at as Time,\r\nevent.metrics.project.name as ProjectName,\r\nevent.metrics.tag as Version,\r\nevent.metrics.description as Description\r\nfrom test.git_json where event.repo == 'Gitlab' and  event.metrics.object_kind == 'release' SETTINGS describe_extend_object_types=1;"
      }
     ]
    },
    {
     "title": "Gitlab Wiki Page Event",
     "type": "table",
     "description": "{\n  \"object_kind\": \"wiki_page\",\n  \"user\": {\n    \"id\": 1,\n    \"name\": \"Administrator\",\n    \"username\": \"root\",\n    \"avatar_url\": \"http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80\\u0026d=identicon\",\n    \"email\": \"admin@example.com\"\n  },\n  \"project\": {\n    \"id\": 1,\n    \"name\": \"awesome-project\",\n    \"description\": \"This is awesome\",\n    \"web_url\": \"http://example.com/root/awesome-project\",\n    \"avatar_url\": null,\n    \"git_ssh_url\": \"git@example.com:root/awesome-project.git\",\n    \"git_http_url\": \"http://example.com/root/awesome-project.git\",\n    \"namespace\": \"root\",\n    \"visibility_level\": 0,\n    \"path_with_namespace\": \"root/awesome-project\",\n    \"default_branch\": \"master\",\n    \"homepage\": \"http://example.com/root/awesome-project\",\n    \"url\": \"git@example.com:root/awesome-project.git\",\n    \"ssh_url\": \"git@example.com:root/awesome-project.git\",\n    \"http_url\": \"http://example.com/root/awesome-project.git\"\n  },\n  \"wiki\": {\n    \"web_url\": \"http://example.com/root/awesome-project/-/wikis/home\",\n    \"git_ssh_url\": \"git@example.com:root/awesome-project.wiki.git\",\n    \"git_http_url\": \"http://example.com/root/awesome-project.wiki.git\",\n    \"path_with_namespace\": \"root/awesome-project.wiki\",\n    \"default_branch\": \"master\"\n  },\n  \"object_attributes\": {\n    \"title\": \"Awesome\",\n    \"content\": \"awesome content goes here\",\n    \"format\": \"markdown\",\n    \"message\": \"adding an awesome page to the wiki\",\n    \"slug\": \"awesome\",\n    \"url\": \"http://example.com/root/awesome-project/-/wikis/awesome\",\n    \"action\": \"create\"\n  }\n}",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "select event.metrics.object_kind as Event,\r\nevent.metrics.object_attributes.title as WikiTitle,\r\nevent.metrics.object_attributes.message as message,\r\nevent.metrics.project.name as ProjectName\r\nfrom test.git_json where event.repo == 'Gitlab' and event.metrics.object_kind == 'wiki_page' SETTINGS describe_extend_object_types=1;"
      }
     ]
    },
    {
     "title": "Gitlab Member Update Event",
     "type": "table",
     "description": "{\n  \"created_at\": \"2020-12-11T04:57:22Z\",\n  \"updated_at\": \"2020-12-12T08:48:19Z\",\n  \"group_name\": \"webhook-test\",\n  \"group_path\": \"webhook-test\",\n  \"group_id\": 100,\n  \"user_username\": \"test_user\",\n  \"user_name\": \"Test User\",\n  \"user_email\": \"testuser@webhooktest.com\",\n  \"user_id\": 64,\n  \"group_access\": \"Developer\",\n  \"group_plan\": null,\n  \"expires_at\": \"2020-12-20T00:00:00Z\",\n  \"event_name\": \"user_update_for_group\"\n}",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "select event.metrics.event_name as Event,\r\nevent.metrics.group_name as GroupName,\r\nevent.metrics.user_name as MemberAdded,\r\nevent.metrics.group_access as MemberAccess\r\nfrom test.git_json where event.repo == 'Gitlab' and  event.metrics.event_name == 'user_update_for_group' SETTINGS describe_extend_object_types=1;"
      }
     ]
    },
    {
     "title": "Gitlab Member Remove Event",
     "type": "table",
     "description": "{\n  \"created_at\": \"2020-12-11T04:57:22Z\",\n  \"updated_at\": \"2020-12-12T08:52:34Z\",\n  \"group_name\": \"webhook-test\",\n  \"group_path\": \"webhook-test\",\n  \"group_id\": 100,\n  \"user_username\": \"test_user\",\n  \"user_name\": \"Test User\",\n  \"user_email\": \"testuser@webhooktest.com\",\n  \"user_id\": 64,\n  \"group_access\": \"Guest\",\n  \"group_plan\": null,\n  \"expires_at\": \"2020-12-14T00:00:00Z\",\n  \"event_name\": \"user_remove_from_group\"\n}",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "rawSql": "select event.metrics.event_name as Event,\r\nevent.metrics.group_name as GroupName,\r\nevent.metrics.user_name as MemberAdded,\r\nevent.metrics.group_access as MemberAccess\r\nfrom test.git_json where event.repo == 'Gitlab' and  event.metrics.event_name == 'user_remove_from_group' SETTINGS describe_extend_object_types=1;"
      }
     ]
    },
    {
     "title": "Gitlab Member Add Event",
     "type": "table",
     "description": "{\n  \"created_at\": \"2020-12-11T04:57:22Z\",\n  \"updated_at\": \"2020-12-11T04:57:22Z\",\n  \"group_name\": \"webhook-test\",\n  \"group_path\": \"webhook-test\",\n  \"group_id\": 100,\n  \"user_username\": \"test_user\",\n  \"user_name\": \"Test User\",\n  \"user_email\": \"testuser@webhooktest.com\",\n  \"user_id\": 64,\n  \"group_access\": \"Guest\",\n  \"group_plan\": null,\n  \"expires_at\": \"2020-12-14T00:00:00Z\",\n  \"event_name\": \"user_add_to_group\"\n}",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "select event.metrics.event_name as Event,\r\nevent.metrics.group_name as GroupName,\r\nevent.metrics.user_name as MemberAdded,\r\nevent.metrics.group_access as MemberAccess\r\nfrom test.git_json where event.repo == 'Gitlab' and  event.metrics.event_name == 'user_add_to_group' SETTINGS describe_extend_object_types=1;"
      }
     ]
    },
    {
     "title": "Gitlab Deployment Event",
     "type": "table",
     "description": "{\n  \"object_kind\": \"deployment\",\n  \"status\": \"success\",\n  \"status_changed_at\":\"2021-04-28 21:50:00 +0200\",\n  \"deployment_id\": 15,\n  \"deployable_id\": 796,\n  \"deployable_url\": \"http://10.126.0.2:3000/root/test-deployment-webhooks/-/jobs/796\",\n  \"environment\": \"staging\",\n  \"project\": {\n    \"id\": 30,\n    \"name\": \"test-deployment-webhooks\",\n    \"description\": \"\",\n    \"web_url\": \"http://10.126.0.2:3000/root/test-deployment-webhooks\",\n    \"avatar_url\": null,\n    \"git_ssh_url\": \"ssh://vlad@10.126.0.2:2222/root/test-deployment-webhooks.git\",\n    \"git_http_url\": \"http://10.126.0.2:3000/root/test-deployment-webhooks.git\",\n    \"namespace\": \"Administrator\",\n    \"visibility_level\": 0,\n    \"path_with_namespace\": \"root/test-deployment-webhooks\",\n    \"default_branch\": \"master\",\n    \"ci_config_path\": \"\",\n    \"homepage\": \"http://10.126.0.2:3000/root/test-deployment-webhooks\",\n    \"url\": \"ssh://vlad@10.126.0.2:2222/root/test-deployment-webhooks.git\",\n    \"ssh_url\": \"ssh://vlad@10.126.0.2:2222/root/test-deployment-webhooks.git\",\n    \"http_url\": \"http://10.126.0.2:3000/root/test-deployment-webhooks.git\"\n  },\n  \"short_sha\": \"279484c0\",\n  \"user\": {\n    \"id\": 1,\n    \"name\": \"Administrator\",\n    \"username\": \"root\",\n    \"avatar_url\": \"https://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=80&d=identicon\",\n    \"email\": \"admin@example.com\"\n  },\n  \"user_url\": \"http://10.126.0.2:3000/root\",\n  \"commit_url\": \"http://10.126.0.2:3000/root/test-deployment-webhooks/-/commit/279484c09fbe69ededfced8c1bb6e6d24616b468\",\n  \"commit_title\": \"Add new file\"\n}",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "select event.metrics.object_kind as Event,\r\nevent.metrics.status as DeploymentStatus,\r\nevent.metrics.project.name as ProjectName,\r\nevent.metrics.user.name as User\r\nfrom test.git_json where event.repo == 'Gitlab' and event.metrics.object_kind == 'deployment' SETTINGS describe_extend_object_types=1;"
      }
     ]
    },
    {
     "title": "Gitlab Issue Event",
     "type": "table",
     "description": "{\n  \"object_kind\": \"issue\",\n  \"event_type\": \"issue\",\n  \"user\": {\n    \"id\": 1,\n    \"name\": \"Administrator\",\n    \"username\": \"root\",\n    \"avatar_url\": \"http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40\\u0026d=identicon\",\n    \"email\": \"admin@example.com\"\n  },\n  \"project\": {\n    \"id\": 1,\n    \"name\":\"Gitlab Test\",\n    \"description\":\"Aut reprehenderit ut est.\",\n    \"web_url\":\"http://example.com/gitlabhq/gitlab-test\",\n    \"avatar_url\":null,\n    \"git_ssh_url\":\"git@example.com:gitlabhq/gitlab-test.git\",\n    \"git_http_url\":\"http://example.com/gitlabhq/gitlab-test.git\",\n    \"namespace\":\"GitlabHQ\",\n    \"visibility_level\":20,\n    \"path_with_namespace\":\"gitlabhq/gitlab-test\",\n    \"default_branch\":\"master\",\n    \"ci_config_path\": null,\n    \"homepage\":\"http://example.com/gitlabhq/gitlab-test\",\n    \"url\":\"http://example.com/gitlabhq/gitlab-test.git\",\n    \"ssh_url\":\"git@example.com:gitlabhq/gitlab-test.git\",\n    \"http_url\":\"http://example.com/gitlabhq/gitlab-test.git\"\n  },\n  \"object_attributes\": {\n    \"id\": 301,\n    \"title\": \"New API: create/update/delete file\",\n    \"assignee_ids\": [51],\n    \"assignee_id\": 51,\n    \"author_id\": 51,\n    \"project_id\": 14,\n    \"created_at\": \"2013-12-03T17:15:43Z\",\n    \"updated_at\": \"2013-12-03T17:15:43Z\",\n    \"updated_by_id\": 1,\n    \"last_edited_at\": null,\n    \"last_edited_by_id\": null,\n    \"relative_position\": 0,\n    \"description\": \"Create new API for manipulations with repository\",\n    \"milestone_id\": null,\n    \"state_id\": 1,\n    \"confidential\": false,\n    \"discussion_locked\": true,\n    \"due_date\": null,\n    \"moved_to_id\": null,\n    \"duplicated_to_id\": null,\n    \"time_estimate\": 0,\n    \"total_time_spent\": 0,\n    \"time_change\": 0,\n    \"human_total_time_spent\": null,\n    \"human_time_estimate\": null,\n    \"human_time_change\": null,\n    \"weight\": null,\n    \"iid\": 23,\n    \"url\": \"http://example.com/diaspora/issues/23\",\n    \"state\": \"opened\",\n    \"action\": \"open\",\n    \"severity\": \"high\",\n    \"escalation_status\": \"triggered\",\n    \"escalation_policy\": {\n      \"id\": 18,\n      \"name\": \"Engineering On-call\"\n    },\n    \"labels\": [{\n        \"id\": 206,\n        \"title\": \"API\",\n        \"color\": \"#ffffff\",\n        \"project_id\": 14,\n        \"created_at\": \"2013-12-03T17:15:43Z\",\n        \"updated_at\": \"2013-12-03T17:15:43Z\",\n        \"template\": false,\n        \"description\": \"API related issues\",\n        \"type\": \"ProjectLabel\",\n        \"group_id\": 41\n      }]\n  },\n  \"repository\": {\n    \"name\": \"Gitlab Test\",\n    \"url\": \"http://example.com/gitlabhq/gitlab-test.git\",\n    \"description\": \"Aut reprehenderit ut est.\",\n    \"homepage\": \"http://example.com/gitlabhq/gitlab-test\"\n  },\n  \"assignees\": [{\n    \"name\": \"User1\",\n    \"username\": \"user1\",\n    \"avatar_url\": \"http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40\\u0026d=identicon\"\n  }],\n  \"assignee\": {\n    \"name\": \"User1\",\n    \"username\": \"user1\",\n    \"avatar_url\": \"http://www.gravatar.com/avatar/e64c7d89f26bd1972efa854d13d7dd61?s=40\\u0026d=identicon\"\n  },\n  \"labels\": [{\n    \"id\": 206,\n    \"title\": \"API\",\n    \"color\": \"#ffffff\",\n    \"project_id\": 14,\n    \"created_at\": \"2013-12-03T17:15:43Z\",\n    \"updated_at\": \"2013-12-03T17:15:43Z\",\n    \"template\": false,\n    \"description\": \"API related issues\",\n    \"type\": \"ProjectLabel\",\n    \"group_id\": 41\n  }],\n  \"changes\": {\n    \"updated_by_id\": {\n      \"previous\": null,\n      \"current\": 1\n    },\n    \"updated_at\": {\n      \"previous\": \"2017-09-15 16:50:55 UTC\",\n      \"current\": \"2017-09-15 16:52:00 UTC\"\n    },\n    \"labels\": {\n      \"previous\": [{\n        \"id\": 206,\n        \"title\": \"API\",\n        \"color\": \"#ffffff\",\n        \"project_id\": 14,\n        \"created_at\": \"2013-12-03T17:15:43Z\",\n        \"updated_at\": \"2013-12-03T17:15:43Z\",\n        \"template\": false,\n        \"description\": \"API related issues\",\n        \"type\": \"ProjectLabel\",\n        \"group_id\": 41\n      }],\n      \"current\": [{\n        \"id\": 205,\n        \"title\": \"Platform\",\n        \"color\": \"#123123\",\n        \"project_id\": 14,\n        \"created_at\": \"2013-12-03T17:15:43Z\",\n        \"updated_at\": \"2013-12-03T17:15:43Z\",\n        \"template\": false,\n        \"description\": \"Platform related issues\",\n        \"type\": \"ProjectLabel\",\n        \"group_id\": 41\n      }]\n    }\n  }\n}",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "select event.metrics.object_attributes.action as IssueAction,\r\nevent.metrics.event_type as Event,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.object_attributes.created_at as Time\r\nfrom test.git_json where event.repo == 'Gitlab' and event.metrics.event_type == 'issue' SETTINGS describe_extend_object_types=1;"
      }
     ]
    },
    {
     "title": "Gitlab Tag Push Event",
     "type": "table",
     "description": "{\n  \"object_kind\": \"tag_push\",\n  \"event_name\": \"tag_push\",\n  \"before\": \"0000000000000000000000000000000000000000\",\n  \"after\": \"82b3d5ae55f7080f1e6022629cdb57bfae7cccc7\",\n  \"ref\": \"refs/tags/v1.0.0\",\n  \"checkout_sha\": \"82b3d5ae55f7080f1e6022629cdb57bfae7cccc7\",\n  \"user_id\": 1,\n  \"user_name\": \"John Smith\",\n  \"user_avatar\": \"https://s.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?s=8://s.gravatar.com/avatar/d4c74594d841139328695756648b6bd6?s=80\",\n  \"project_id\": 1,\n  \"project\":{\n    \"id\": 1,\n    \"name\":\"Example\",\n    \"description\":\"\",\n    \"web_url\":\"http://example.com/jsmith/example\",\n    \"avatar_url\":null,\n    \"git_ssh_url\":\"git@example.com:jsmith/example.git\",\n    \"git_http_url\":\"http://example.com/jsmith/example.git\",\n    \"namespace\":\"Jsmith\",\n    \"visibility_level\":0,\n    \"path_with_namespace\":\"jsmith/example\",\n    \"default_branch\":\"master\",\n    \"homepage\":\"http://example.com/jsmith/example\",\n    \"url\":\"git@example.com:jsmith/example.git\",\n    \"ssh_url\":\"git@example.com:jsmith/example.git\",\n    \"http_url\":\"http://example.com/jsmith/example.git\"\n  },\n  \"repository\":{\n    \"name\": \"Example\",\n    \"url\": \"ssh://git@example.com/jsmith/example.git\",\n    \"description\": \"\",\n    \"homepage\": \"http://example.com/jsmith/example\",\n    \"git_http_url\":\"http://example.com/jsmith/example.git\",\n    \"git_ssh_url\":\"git@example.com:jsmith/example.git\",\n    \"visibility_level\":0\n  },\n  \"commits\": [],\n  \"total_commits_count\": 0\n}",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "select event.metrics.event_name as Event,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.ref as tag\r\nfrom test.git_json where event.repo == 'Gitlab' and event.metrics.event_name == 'tag_push' SETTINGS describe_extend_object_types=1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Gitea Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gitea push event",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "select event.metrics.after as hashid,\r\nevent.metrics.repository.name as repo,\r\nevent.metrics.commits.committer.name[1] as committer,\r\nevent.metrics.commits.message[1] as message,\r\nevent.metrics.commits.timestamp as time\r\nfrom test.git_json where event.repo =='Gitea' and event.repo != 'Github' SETTINGS describe_extend_object_types=1;"
      }
     ]
    }
   ]
  },
  { "title": "Github Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Github Issue Event",
   "type": "table",
   "description": "{\n  \"action\": \"edited\",\n  \"issue\": {\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/1\",\n    \"repository_url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/1/labels{/name}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/1/comments\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/1/events\",\n    \"html_url\": \"https://github.com/Codertocat/Hello-World/issues/1\",\n    \"id\": 444500041,\n    \"node_id\": \"MDU6SXNzdWU0NDQ1MDAwNDE=\",\n    \"number\": 1,\n    \"title\": \"Spelling error in the README file\",\n    \"user\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"labels\": [\n      {\n        \"id\": 1362934389,\n        \"node_id\": \"MDU6TGFiZWwxMzYyOTM0Mzg5\",\n        \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels/bug\",\n        \"name\": \"bug\",\n        \"color\": \"d73a4a\",\n        \"default\": true\n      }\n    ],\n    \"state\": \"open\",\n    \"locked\": false,\n    \"assignee\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"assignees\": [\n      {\n        \"login\": \"Codertocat\",\n        \"id\": 21031067,\n        \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n        \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n        \"gravatar_id\": \"\",\n        \"url\": \"https://api.github.com/users/Codertocat\",\n        \"html_url\": \"https://github.com/Codertocat\",\n        \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n        \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n        \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n        \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n        \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n        \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n        \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n        \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n        \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n        \"type\": \"User\",\n        \"site_admin\": false\n      }\n    ],\n    \"milestone\": {\n      \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones/1\",\n      \"html_url\": \"https://github.com/Codertocat/Hello-World/milestone/1\",\n      \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones/1/labels\",\n      \"id\": 4317517,\n      \"node_id\": \"MDk6TWlsZXN0b25lNDMxNzUxNw==\",\n      \"number\": 1,\n      \"title\": \"v1.0\",\n      \"description\": \"Add new space flight simulator\",\n      \"creator\": {\n        \"login\": \"Codertocat\",\n        \"id\": 21031067,\n        \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n        \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n        \"gravatar_id\": \"\",\n        \"url\": \"https://api.github.com/users/Codertocat\",\n        \"html_url\": \"https://github.com/Codertocat\",\n        \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n        \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n        \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n        \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n        \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n        \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n        \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n        \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n        \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n        \"type\": \"User\",\n        \"site_admin\": false\n      },\n      \"open_issues\": 1,\n      \"closed_issues\": 0,\n      \"state\": \"closed\",\n      \"created_at\": \"2019-05-15T15:20:17Z\",\n      \"updated_at\": \"2019-05-15T15:20:18Z\",\n      \"due_on\": \"2019-05-23T07:00:00Z\",\n      \"closed_at\": \"2019-05-15T15:20:18Z\"\n    },\n    \"comments\": 0,\n    \"created_at\": \"2019-05-15T15:20:18Z\",\n    \"updated_at\": \"2019-05-15T15:20:18Z\",\n    \"closed_at\": null,\n    \"author_association\": \"OWNER\",\n    \"body\": \"It looks like you accidently spelled 'commit' with two 't's.\"\n  },\n  \"changes\": {},\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:19:27Z\",\n    \"pushed_at\": \"2019-05-15T15:20:13Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": null,\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 1,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 1,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as AlertAction,\r\nevent.metrics.issue.title as IssueTitle,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.issue.labels.name[1] as Label\r\nfrom test.git_json where event.repo == 'Github' and  event.metrics.issue.title !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github repository_vulnerability_alert",
   "type": "table",
   "description": "{\n  \"action\": \"create\",\n  \"alert\": {\n    \"id\": 91095730,\n    \"affected_range\": \">= 2.0.4, < 2.0.6\",\n    \"affected_package_name\": \"rack\",\n    \"fixed_in\": \"2.0.6\",\n    \"external_reference\": \"https://nvd.nist.gov/vuln/detail/CVE-2018-16470\",\n    \"external_identifier\": \"CVE-2018-16470\",\n    \"severity\": \"moderate\",\n    \"ghsa_id\": \"GHSA-hg78-4f6x-99wq\",\n    \"created_at\": \"2021-03-01T01:23:45Z\"\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:19:27Z\",\n    \"pushed_at\": \"2019-05-15T15:20:32Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": null,\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"github\",\n    \"id\": 9919,\n    \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjk5MTk=\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/9919?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/github\",\n    \"html_url\": \"https://github.com/github\",\n    \"followers_url\": \"https://api.github.com/users/github/followers\",\n    \"following_url\": \"https://api.github.com/users/github/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/github/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/github/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/github/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/github/orgs\",\n    \"repos_url\": \"https://api.github.com/users/github/repos\",\n    \"events_url\": \"https://api.github.com/users/github/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/github/received_events\",\n    \"type\": \"Organization\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as AlertAction,\r\nevent.metrics.alert.created_at as AlertTime,\r\nevent.metrics.repository.name as RepoName\r\nfrom test.git_json where event.repo == 'Github' and  event.metrics.alert.created_at !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Member Event",
   "type": "table",
   "description": "{\n  \"action\": \"added\",\n  \"member\": {\n    \"login\": \"hacktocat\",\n    \"id\": 39652351,\n    \"node_id\": \"MDQ6VXNlcjM5NjUyMzUx\",\n    \"avatar_url\": \"https://avatars2.githubusercontent.com/u/39652351?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/hacktocat\",\n    \"html_url\": \"https://github.com/hacktocat\",\n    \"followers_url\": \"https://api.github.com/users/hacktocat/followers\",\n    \"following_url\": \"https://api.github.com/users/hacktocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/hacktocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/hacktocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/hacktocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/hacktocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/hacktocat/repos\",\n    \"events_url\": \"https://api.github.com/users/hacktocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/hacktocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:20:41Z\",\n    \"pushed_at\": \"2019-05-15T15:20:57Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 1,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 1,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"hacktocat\",\n    \"id\": 39652351,\n    \"node_id\": \"MDQ6VXNlcjM5NjUyMzUx\",\n    \"avatar_url\": \"https://avatars2.githubusercontent.com/u/39652351?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/hacktocat\",\n    \"html_url\": \"https://github.com/hacktocat\",\n    \"followers_url\": \"https://api.github.com/users/hacktocat/followers\",\n    \"following_url\": \"https://api.github.com/users/hacktocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/hacktocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/hacktocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/hacktocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/hacktocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/hacktocat/repos\",\n    \"events_url\": \"https://api.github.com/users/hacktocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/hacktocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as MemberAction,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.member.login as AddedMember\r\nfrom test.git_json where event.repo == 'Github' and  event.metrics.member.login !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Team Add Event",
   "type": "table",
   "description": "{\n  \"team\": {\n    \"name\": \"github\",\n    \"id\": 3253328,\n    \"node_id\": \"MDQ6VGVhbTMyNTMzMjg=\",\n    \"slug\": \"github\",\n    \"description\": \"Open-source team\",\n    \"privacy\": \"secret\",\n    \"url\": \"https://api.github.com/teams/3253328\",\n    \"html_url\": \"https://github.com/orgs/Octocoders/teams/github\",\n    \"members_url\": \"https://api.github.com/teams/3253328/members{/member}\",\n    \"repositories_url\": \"https://api.github.com/teams/3253328/repos\",\n    \"permission\": \"pull\"\n  },\n  \"repository\": {\n    \"id\": 186853261,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMyNjE=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Octocoders/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Octocoders\",\n      \"id\": 38302899,\n      \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/38302899?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Octocoders\",\n      \"html_url\": \"https://github.com/Octocoders\",\n      \"followers_url\": \"https://api.github.com/users/Octocoders/followers\",\n      \"following_url\": \"https://api.github.com/users/Octocoders/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Octocoders/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Octocoders/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Octocoders/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Octocoders/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Octocoders/repos\",\n      \"events_url\": \"https://api.github.com/users/Octocoders/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Octocoders/received_events\",\n      \"type\": \"Organization\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Octocoders/Hello-World\",\n    \"description\": null,\n    \"fork\": true,\n    \"url\": \"https://api.github.com/repos/Octocoders/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Octocoders/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Octocoders/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Octocoders/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Octocoders/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Octocoders/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Octocoders/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Octocoders/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Octocoders/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Octocoders/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Octocoders/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Octocoders/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Octocoders/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Octocoders/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Octocoders/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Octocoders/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Octocoders/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Octocoders/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Octocoders/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Octocoders/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Octocoders/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Octocoders/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Octocoders/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Octocoders/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Octocoders/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Octocoders/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Octocoders/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Octocoders/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Octocoders/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Octocoders/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Octocoders/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Octocoders/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:20:42Z\",\n    \"updated_at\": \"2019-05-15T15:20:45Z\",\n    \"pushed_at\": \"2019-05-15T15:20:33Z\",\n    \"git_url\": \"git://github.com/Octocoders/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Octocoders/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Octocoders/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Octocoders/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": false,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": false,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 0,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 0,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"organization\": {\n    \"login\": \"Octocoders\",\n    \"id\": 38302899,\n    \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5\",\n    \"url\": \"https://api.github.com/orgs/Octocoders\",\n    \"repos_url\": \"https://api.github.com/orgs/Octocoders/repos\",\n    \"events_url\": \"https://api.github.com/orgs/Octocoders/events\",\n    \"hooks_url\": \"https://api.github.com/orgs/Octocoders/hooks\",\n    \"issues_url\": \"https://api.github.com/orgs/Octocoders/issues\",\n    \"members_url\": \"https://api.github.com/orgs/Octocoders/members{/member}\",\n    \"public_members_url\": \"https://api.github.com/orgs/Octocoders/public_members{/member}\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/38302899?v=4\",\n    \"description\": \"\"\n  },\n  \"sender\": {\n    \"login\": \"Octocoders\",\n    \"id\": 38302899,\n    \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/38302899?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Octocoders\",\n    \"html_url\": \"https://github.com/Octocoders\",\n    \"followers_url\": \"https://api.github.com/users/Octocoders/followers\",\n    \"following_url\": \"https://api.github.com/users/Octocoders/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Octocoders/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Octocoders/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Octocoders/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Octocoders/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Octocoders/repos\",\n    \"events_url\": \"https://api.github.com/users/Octocoders/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Octocoders/received_events\",\n    \"type\": \"Organization\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select event.metrics.team.name as TeamName,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.sender.login as Author\r\nfrom test.git_json where event.repo == 'Github' and  event.metrics.team.name !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Starred Event",
   "type": "table",
   "description": "{\n  \"action\": \"created\",\n  \"starred_at\": \"2019-05-15T15:20:40Z\",\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:20:40Z\",\n    \"pushed_at\": \"2019-05-15T15:20:33Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 1,\n    \"watchers_count\": 1,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 2,\n    \"watchers\": 1,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as StarAction,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.starred_at as StarredAt,\r\nevent.metrics.sender.login as Author\r\nfrom test.git_json where event.repo == 'Github' and  event.metrics.starred_at !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Milestone Event",
   "type": "table",
   "description": "{\n  \"action\": \"created\",\n  \"milestone\": {\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones/1\",\n    \"html_url\": \"https://github.com/Codertocat/Hello-World/milestone/1\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones/1/labels\",\n    \"id\": 4317517,\n    \"node_id\": \"MDk6TWlsZXN0b25lNDMxNzUxNw==\",\n    \"number\": 1,\n    \"title\": \"v1.0\",\n    \"description\": \"Add new space flight simulator\",\n    \"creator\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"open_issues\": 0,\n    \"closed_issues\": 0,\n    \"state\": \"open\",\n    \"created_at\": \"2019-05-15T15:20:17Z\",\n    \"updated_at\": \"2019-05-15T15:20:17Z\",\n    \"due_on\": \"2019-05-23T07:00:00Z\",\n    \"closed_at\": null\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:19:27Z\",\n    \"pushed_at\": \"2019-05-15T15:20:13Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": null,\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 0,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 0,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as MilestoneAction,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.milestone.description as Description,\r\nevent.metrics.sender.login as Author\r\nfrom test.git_json where event.repo == 'Github' and  event.metrics.milestone.description !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Label Event",
   "type": "table",
   "description": "{\n  \"action\": \"deleted\",\n  \"label\": {\n    \"id\": 1362937026,\n    \"node_id\": \"MDU6TGFiZWwxMzYyOTM3MDI2\",\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels/:bug:%20Bugfix\",\n    \"name\": \":bug: Bugfix\",\n    \"color\": \"cceeaa\",\n    \"default\": false\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:21:03Z\",\n    \"pushed_at\": \"2019-05-15T15:20:57Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 1,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 1,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as LabelAction,\r\nevent.metrics.label.name as Label,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.sender.login as Author\r\nfrom test.git_json where event.repo == 'Github' and event.metrics.label.name !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Deployment Event",
   "type": "table",
   "description": "{\n  \"action\": \"created\",\n  \"deployment\": {\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments/145988746\",\n    \"id\": 145988746,\n    \"node_id\": \"MDEwOkRlcGxveW1lbnQxNDU5ODg3NDY=\",\n    \"sha\": \"f95f852bd8fca8fcc58a9a2d6c842781e32a215e\",\n    \"ref\": \"master\",\n    \"task\": \"deploy\",\n    \"payload\": {},\n    \"original_environment\": \"production\",\n    \"environment\": \"production\",\n    \"description\": null,\n    \"creator\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"created_at\": \"2019-05-15T15:20:53Z\",\n    \"updated_at\": \"2019-05-15T15:20:53Z\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments/145988746/statuses\",\n    \"repository_url\": \"https://api.github.com/repos/Codertocat/Hello-World\"\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:20:41Z\",\n    \"pushed_at\": \"2019-05-15T15:20:52Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 1,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 1,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as DeploymentAction,\r\nevent.metrics.deployment.environment as DeploymentEnvironment,\r\nevent.metrics.sender.login as Author\r\nfrom test.git_json where event.repo == 'Github' and event.metrics.deployment.environment !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Checkrun Event",
   "type": "table",
   "description": "{\n  \"action\": \"created\",\n  \"check_run\": {\n    \"id\": 128620228,\n    \"node_id\": \"MDg6Q2hlY2tSdW4xMjg2MjAyMjg=\",\n    \"head_sha\": \"ec26c3e57ca3a959ca5aad62de7213c562f8c821\",\n    \"external_id\": \"\",\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/check-runs/128620228\",\n    \"html_url\": \"https://github.com/Codertocat/Hello-World/runs/128620228\",\n    \"details_url\": \"https://octocoders.github.io\",\n    \"status\": \"queued\",\n    \"conclusion\": null,\n    \"started_at\": \"2019-05-15T15:21:12Z\",\n    \"completed_at\": null,\n    \"output\": {\n      \"title\": null,\n      \"summary\": null,\n      \"text\": null,\n      \"annotations_count\": 0,\n      \"annotations_url\": \"https://api.github.com/repos/Codertocat/Hello-World/check-runs/128620228/annotations\"\n    },\n    \"name\": \"Octocoders-linter\",\n    \"check_suite\": {\n      \"id\": 118578147,\n      \"node_id\": \"MDEwOkNoZWNrU3VpdGUxMTg1NzgxNDc=\",\n      \"head_branch\": \"changes\",\n      \"head_sha\": \"ec26c3e57ca3a959ca5aad62de7213c562f8c821\",\n      \"status\": \"queued\",\n      \"conclusion\": null,\n      \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/check-suites/118578147\",\n      \"before\": \"6113728f27ae82c7b1a177c8d03f9e96e0adf246\",\n      \"after\": \"ec26c3e57ca3a959ca5aad62de7213c562f8c821\",\n      \"pull_requests\": [\n        {\n          \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2\",\n          \"id\": 279147437,\n          \"number\": 2,\n          \"head\": {\n            \"ref\": \"changes\",\n            \"sha\": \"ec26c3e57ca3a959ca5aad62de7213c562f8c821\",\n            \"repo\": {\n              \"id\": 186853002,\n              \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n              \"name\": \"Hello-World\"\n            }\n          },\n          \"base\": {\n            \"ref\": \"master\",\n            \"sha\": \"f95f852bd8fca8fcc58a9a2d6c842781e32a215e\",\n            \"repo\": {\n              \"id\": 186853002,\n              \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n              \"name\": \"Hello-World\"\n            }\n          }\n        }\n      ],\n      \"app\": {\n        \"id\": 29310,\n        \"node_id\": \"MDM6QXBwMjkzMTA=\",\n        \"owner\": {\n          \"login\": \"Octocoders\",\n          \"id\": 38302899,\n          \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5\",\n          \"avatar_url\": \"https://avatars1.githubusercontent.com/u/38302899?v=4\",\n          \"gravatar_id\": \"\",\n          \"url\": \"https://api.github.com/users/Octocoders\",\n          \"html_url\": \"https://github.com/Octocoders\",\n          \"followers_url\": \"https://api.github.com/users/Octocoders/followers\",\n          \"following_url\": \"https://api.github.com/users/Octocoders/following{/other_user}\",\n          \"gists_url\": \"https://api.github.com/users/Octocoders/gists{/gist_id}\",\n          \"starred_url\": \"https://api.github.com/users/Octocoders/starred{/owner}{/repo}\",\n          \"subscriptions_url\": \"https://api.github.com/users/Octocoders/subscriptions\",\n          \"organizations_url\": \"https://api.github.com/users/Octocoders/orgs\",\n          \"repos_url\": \"https://api.github.com/users/Octocoders/repos\",\n          \"events_url\": \"https://api.github.com/users/Octocoders/events{/privacy}\",\n          \"received_events_url\": \"https://api.github.com/users/Octocoders/received_events\",\n          \"type\": \"Organization\",\n          \"site_admin\": false\n        },\n        \"name\": \"octocoders-linter\",\n        \"description\": \"\",\n        \"external_url\": \"https://octocoders.github.io\",\n        \"html_url\": \"https://github.com/apps/octocoders-linter\",\n        \"created_at\": \"2019-04-19T19:36:24Z\",\n        \"updated_at\": \"2019-04-19T19:36:56Z\",\n        \"permissions\": {\n          \"administration\": \"write\",\n          \"checks\": \"write\",\n          \"contents\": \"write\",\n          \"deployments\": \"write\",\n          \"issues\": \"write\",\n          \"members\": \"write\",\n          \"metadata\": \"read\",\n          \"organization_administration\": \"write\",\n          \"organization_hooks\": \"write\",\n          \"organization_plan\": \"read\",\n          \"organization_projects\": \"write\",\n          \"organization_user_blocking\": \"write\",\n          \"pages\": \"write\",\n          \"pull_requests\": \"write\",\n          \"repository_hooks\": \"write\",\n          \"repository_projects\": \"write\",\n          \"statuses\": \"write\",\n          \"team_discussions\": \"write\",\n          \"vulnerability_alerts\": \"read\"\n        },\n        \"events\": []\n      },\n      \"created_at\": \"2019-05-15T15:20:31Z\",\n      \"updated_at\": \"2019-05-15T15:20:31Z\"\n    },\n    \"app\": {\n      \"id\": 29310,\n      \"node_id\": \"MDM6QXBwMjkzMTA=\",\n      \"owner\": {\n        \"login\": \"Octocoders\",\n        \"id\": 38302899,\n        \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5\",\n        \"avatar_url\": \"https://avatars1.githubusercontent.com/u/38302899?v=4\",\n        \"gravatar_id\": \"\",\n        \"url\": \"https://api.github.com/users/Octocoders\",\n        \"html_url\": \"https://github.com/Octocoders\",\n        \"followers_url\": \"https://api.github.com/users/Octocoders/followers\",\n        \"following_url\": \"https://api.github.com/users/Octocoders/following{/other_user}\",\n        \"gists_url\": \"https://api.github.com/users/Octocoders/gists{/gist_id}\",\n        \"starred_url\": \"https://api.github.com/users/Octocoders/starred{/owner}{/repo}\",\n        \"subscriptions_url\": \"https://api.github.com/users/Octocoders/subscriptions\",\n        \"organizations_url\": \"https://api.github.com/users/Octocoders/orgs\",\n        \"repos_url\": \"https://api.github.com/users/Octocoders/repos\",\n        \"events_url\": \"https://api.github.com/users/Octocoders/events{/privacy}\",\n        \"received_events_url\": \"https://api.github.com/users/Octocoders/received_events\",\n        \"type\": \"Organization\",\n        \"site_admin\": false\n      },\n      \"name\": \"octocoders-linter\",\n      \"description\": \"\",\n      \"external_url\": \"https://octocoders.github.io\",\n      \"html_url\": \"https://github.com/apps/octocoders-linter\",\n      \"created_at\": \"2019-04-19T19:36:24Z\",\n      \"updated_at\": \"2019-04-19T19:36:56Z\",\n      \"permissions\": {\n        \"administration\": \"write\",\n        \"checks\": \"write\",\n        \"contents\": \"write\",\n        \"deployments\": \"write\",\n        \"issues\": \"write\",\n        \"members\": \"write\",\n        \"metadata\": \"read\",\n        \"organization_administration\": \"write\",\n        \"organization_hooks\": \"write\",\n        \"organization_plan\": \"read\",\n        \"organization_projects\": \"write\",\n        \"organization_user_blocking\": \"write\",\n        \"pages\": \"write\",\n        \"pull_requests\": \"write\",\n        \"repository_hooks\": \"write\",\n        \"repository_projects\": \"write\",\n        \"statuses\": \"write\",\n        \"team_discussions\": \"write\",\n        \"vulnerability_alerts\": \"read\"\n      },\n      \"events\": []\n    },\n    \"pull_requests\": [\n      {\n        \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2\",\n        \"id\": 279147437,\n        \"number\": 2,\n        \"head\": {\n          \"ref\": \"changes\",\n          \"sha\": \"ec26c3e57ca3a959ca5aad62de7213c562f8c821\",\n          \"repo\": {\n            \"id\": 186853002,\n            \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n            \"name\": \"Hello-World\"\n          }\n        },\n        \"base\": {\n          \"ref\": \"master\",\n          \"sha\": \"f95f852bd8fca8fcc58a9a2d6c842781e32a215e\",\n          \"repo\": {\n            \"id\": 186853002,\n            \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n            \"name\": \"Hello-World\"\n          }\n        }\n      }\n    ],\n    \"deployment\": {\n      \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments/326191728\",\n      \"id\": 326191728,\n      \"node_id\": \"MDEwOkRlcGxveW1lbnQzMjYxOTE3Mjg=\",\n      \"task\": \"deploy\",\n      \"original_environment\": \"lab\",\n      \"environment\": \"lab\",\n      \"description\": null,\n      \"created_at\": \"2021-02-18T08:22:48Z\",\n      \"updated_at\": \"2021-02-18T09:47:16Z\",\n      \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments/326191728/statuses\",\n      \"repository_url\": \"https://api.github.com/repos/Codertocat/Hello-World\"\n    }\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:21:03Z\",\n    \"pushed_at\": \"2019-05-15T15:20:57Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 1,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 1,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "select event.metrics.action as Deleted,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.sender.login as Author\r\nfrom test.git_json where event.repo == 'Github' and event.metrics.check_run.node_id != ''  SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Delete Event",
   "type": "table",
   "description": "{\n  \"ref\": \"simple-tag\",\n  \"ref_type\": \"tag\",\n  \"pusher_type\": \"user\",\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:20:41Z\",\n    \"pushed_at\": \"2019-05-15T15:20:57Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 1,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 1,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "select event.metrics.ref_type as Deleted,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.sender.login as DeletedBy\r\nfrom test.git_json where event.repo == 'Github' and event.metrics.ref_type !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Fork Event",
   "type": "table",
   "description": "{\n  \"forkee\": {\n    \"id\": 186853261,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMyNjE=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Octocoders/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Octocoders\",\n      \"id\": 38302899,\n      \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/38302899?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Octocoders\",\n      \"html_url\": \"https://github.com/Octocoders\",\n      \"followers_url\": \"https://api.github.com/users/Octocoders/followers\",\n      \"following_url\": \"https://api.github.com/users/Octocoders/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Octocoders/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Octocoders/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Octocoders/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Octocoders/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Octocoders/repos\",\n      \"events_url\": \"https://api.github.com/users/Octocoders/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Octocoders/received_events\",\n      \"type\": \"Organization\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Octocoders/Hello-World\",\n    \"description\": null,\n    \"fork\": true,\n    \"url\": \"https://api.github.com/repos/Octocoders/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Octocoders/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Octocoders/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Octocoders/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Octocoders/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Octocoders/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Octocoders/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Octocoders/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Octocoders/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Octocoders/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Octocoders/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Octocoders/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Octocoders/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Octocoders/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Octocoders/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Octocoders/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Octocoders/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Octocoders/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Octocoders/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Octocoders/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Octocoders/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Octocoders/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Octocoders/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Octocoders/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Octocoders/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Octocoders/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Octocoders/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Octocoders/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Octocoders/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Octocoders/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Octocoders/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Octocoders/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Octocoders/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:20:42Z\",\n    \"updated_at\": \"2019-05-15T15:20:41Z\",\n    \"pushed_at\": \"2019-05-15T15:20:33Z\",\n    \"git_url\": \"git://github.com/Octocoders/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Octocoders/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Octocoders/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Octocoders/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": null,\n    \"has_issues\": false,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": false,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 0,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 0,\n    \"watchers\": 0,\n    \"default_branch\": \"master\",\n    \"public\": true\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:20:41Z\",\n    \"pushed_at\": \"2019-05-15T15:20:33Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 1,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 1,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Octocoders\",\n    \"id\": 38302899,\n    \"node_id\": \"MDEyOk9yZ2FuaXphdGlvbjM4MzAyODk5\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/38302899?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Octocoders\",\n    \"html_url\": \"https://github.com/Octocoders\",\n    \"followers_url\": \"https://api.github.com/users/Octocoders/followers\",\n    \"following_url\": \"https://api.github.com/users/Octocoders/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Octocoders/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Octocoders/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Octocoders/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Octocoders/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Octocoders/repos\",\n    \"events_url\": \"https://api.github.com/users/Octocoders/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Octocoders/received_events\",\n    \"type\": \"Organization\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "select event.metrics.sender.login as ForkedBy,\r\nevent.metrics.repository.name as RepoName\r\nfrom test.git_json where event.repo == 'Github' and event.metrics.forkee.node_id !='' SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "github pushevent",
   "type": "table",
   "description": "{\n  \"ref\": \"refs/tags/simple-tag\",\n  \"before\": \"0000000000000000000000000000000000000000\",\n  \"after\": \"6113728f27ae82c7b1a177c8d03f9e96e0adf246\",\n  \"created\": true,\n  \"deleted\": false,\n  \"forced\": false,\n  \"base_ref\": null,\n  \"compare\": \"https://github.com/Codertocat/Hello-World/compare/simple-tag\",\n  \"commits\": [],\n  \"head_commit\": {\n    \"id\": \"6113728f27ae82c7b1a177c8d03f9e96e0adf246\",\n    \"tree_id\": \"4b825dc642cb6eb9a060e54bf8d69288fbee4904\",\n    \"distinct\": true,\n    \"message\": \"Adding a .gitignore file\",\n    \"timestamp\": \"2019-05-15T15:20:41Z\",\n    \"url\": \"https://github.com/Codertocat/Hello-World/commit/6113728f27ae82c7b1a177c8d03f9e96e0adf246\",\n    \"author\": {\n      \"name\": \"Codertocat\",\n      \"email\": \"21031067+Codertocat@users.noreply.github.com\",\n      \"username\": \"Codertocat\"\n    },\n    \"committer\": {\n      \"name\": \"Codertocat\",\n      \"email\": \"21031067+Codertocat@users.noreply.github.com\",\n      \"username\": \"Codertocat\"\n    },\n    \"added\": [\n      \".gitignore\"\n    ],\n    \"removed\": [],\n    \"modified\": []\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"name\": \"Codertocat\",\n      \"email\": \"21031067+Codertocat@users.noreply.github.com\",\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://github.com/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": 1557933565,\n    \"updated_at\": \"2019-05-15T15:20:41Z\",\n    \"pushed_at\": 1557933657,\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": \"Ruby\",\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 1,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 1,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\",\n    \"stargazers\": 0,\n    \"master_branch\": \"master\"\n  },\n  \"pusher\": {\n    \"name\": \"Codertocat\",\n    \"email\": \"21031067+Codertocat@users.noreply.github.com\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "select event.metrics.after as hashid, \r\nevent.metrics.repository.name as repo, \r\nevent.metrics.commits.committer.name[1] as committer, \r\nevent.metrics.commits.message[1] as message,\r\nevent.metrics.repository.updated_at as time \r\nfrom test.git_json where event.repo == 'Github' and event.metrics.commits.committer.name[1] != ''  SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Pull Request Event",
   "type": "table",
   "description": "{\n  \"action\": \"opened\",\n  \"number\": 2,\n  \"pull_request\": {\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2\",\n    \"id\": 279147437,\n    \"node_id\": \"MDExOlB1bGxSZXF1ZXN0Mjc5MTQ3NDM3\",\n    \"html_url\": \"https://github.com/Codertocat/Hello-World/pull/2\",\n    \"diff_url\": \"https://github.com/Codertocat/Hello-World/pull/2.diff\",\n    \"patch_url\": \"https://github.com/Codertocat/Hello-World/pull/2.patch\",\n    \"issue_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/2\",\n    \"number\": 2,\n    \"state\": \"open\",\n    \"locked\": false,\n    \"title\": \"Update the README with new information.\",\n    \"user\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"body\": \"This is a pretty simple change that we need to pull into master.\",\n    \"created_at\": \"2019-05-15T15:20:33Z\",\n    \"updated_at\": \"2019-05-15T15:20:33Z\",\n    \"closed_at\": null,\n    \"merged_at\": null,\n    \"merge_commit_sha\": null,\n    \"assignee\": null,\n    \"assignees\": [],\n    \"requested_reviewers\": [],\n    \"requested_teams\": [],\n    \"labels\": [],\n    \"milestone\": null,\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2/commits\",\n    \"review_comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2/comments\",\n    \"review_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/comments{/number}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/2/comments\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/ec26c3e57ca3a959ca5aad62de7213c562f8c821\",\n    \"head\": {\n      \"label\": \"Codertocat:changes\",\n      \"ref\": \"changes\",\n      \"sha\": \"ec26c3e57ca3a959ca5aad62de7213c562f8c821\",\n      \"user\": {\n        \"login\": \"Codertocat\",\n        \"id\": 21031067,\n        \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n        \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n        \"gravatar_id\": \"\",\n        \"url\": \"https://api.github.com/users/Codertocat\",\n        \"html_url\": \"https://github.com/Codertocat\",\n        \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n        \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n        \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n        \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n        \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n        \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n        \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n        \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n        \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n        \"type\": \"User\",\n        \"site_admin\": false\n      },\n      \"repo\": {\n        \"id\": 186853002,\n        \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n        \"name\": \"Hello-World\",\n        \"full_name\": \"Codertocat/Hello-World\",\n        \"private\": false,\n        \"owner\": {\n          \"login\": \"Codertocat\",\n          \"id\": 21031067,\n          \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n          \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n          \"gravatar_id\": \"\",\n          \"url\": \"https://api.github.com/users/Codertocat\",\n          \"html_url\": \"https://github.com/Codertocat\",\n          \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n          \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n          \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n          \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n          \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n          \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n          \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n          \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n          \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n          \"type\": \"User\",\n          \"site_admin\": false\n        },\n        \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n        \"description\": null,\n        \"fork\": false,\n        \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n        \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n        \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n        \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n        \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n        \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n        \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n        \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n        \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n        \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n        \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n        \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n        \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n        \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n        \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n        \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n        \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n        \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n        \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n        \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n        \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n        \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n        \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n        \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n        \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n        \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n        \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n        \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n        \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n        \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n        \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n        \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n        \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n        \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n        \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n        \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n        \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n        \"created_at\": \"2019-05-15T15:19:25Z\",\n        \"updated_at\": \"2019-05-15T15:19:27Z\",\n        \"pushed_at\": \"2019-05-15T15:20:32Z\",\n        \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n        \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n        \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n        \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n        \"homepage\": null,\n        \"size\": 0,\n        \"stargazers_count\": 0,\n        \"watchers_count\": 0,\n        \"language\": null,\n        \"has_issues\": true,\n        \"has_projects\": true,\n        \"has_downloads\": true,\n        \"has_wiki\": true,\n        \"has_pages\": true,\n        \"forks_count\": 0,\n        \"mirror_url\": null,\n        \"archived\": false,\n        \"disabled\": false,\n        \"open_issues_count\": 2,\n        \"license\": null,\n        \"forks\": 0,\n        \"open_issues\": 2,\n        \"watchers\": 0,\n        \"default_branch\": \"master\",\n        \"allow_squash_merge\": true,\n        \"allow_merge_commit\": true,\n        \"allow_rebase_merge\": true,\n        \"delete_branch_on_merge\": false\n      }\n    },\n    \"base\": {\n      \"label\": \"Codertocat:master\",\n      \"ref\": \"master\",\n      \"sha\": \"f95f852bd8fca8fcc58a9a2d6c842781e32a215e\",\n      \"user\": {\n        \"login\": \"Codertocat\",\n        \"id\": 21031067,\n        \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n        \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n        \"gravatar_id\": \"\",\n        \"url\": \"https://api.github.com/users/Codertocat\",\n        \"html_url\": \"https://github.com/Codertocat\",\n        \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n        \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n        \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n        \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n        \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n        \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n        \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n        \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n        \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n        \"type\": \"User\",\n        \"site_admin\": false\n      },\n      \"repo\": {\n        \"id\": 186853002,\n        \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n        \"name\": \"Hello-World\",\n        \"full_name\": \"Codertocat/Hello-World\",\n        \"private\": false,\n        \"owner\": {\n          \"login\": \"Codertocat\",\n          \"id\": 21031067,\n          \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n          \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n          \"gravatar_id\": \"\",\n          \"url\": \"https://api.github.com/users/Codertocat\",\n          \"html_url\": \"https://github.com/Codertocat\",\n          \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n          \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n          \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n          \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n          \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n          \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n          \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n          \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n          \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n          \"type\": \"User\",\n          \"site_admin\": false\n        },\n        \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n        \"description\": null,\n        \"fork\": false,\n        \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n        \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n        \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n        \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n        \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n        \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n        \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n        \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n        \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n        \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n        \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n        \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n        \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n        \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n        \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n        \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n        \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n        \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n        \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n        \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n        \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n        \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n        \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n        \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n        \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n        \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n        \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n        \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n        \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n        \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n        \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n        \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n        \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n        \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n        \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n        \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n        \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n        \"created_at\": \"2019-05-15T15:19:25Z\",\n        \"updated_at\": \"2019-05-15T15:19:27Z\",\n        \"pushed_at\": \"2019-05-15T15:20:32Z\",\n        \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n        \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n        \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n        \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n        \"homepage\": null,\n        \"size\": 0,\n        \"stargazers_count\": 0,\n        \"watchers_count\": 0,\n        \"language\": null,\n        \"has_issues\": true,\n        \"has_projects\": true,\n        \"has_downloads\": true,\n        \"has_wiki\": true,\n        \"has_pages\": true,\n        \"forks_count\": 0,\n        \"mirror_url\": null,\n        \"archived\": false,\n        \"disabled\": false,\n        \"open_issues_count\": 2,\n        \"license\": null,\n        \"forks\": 0,\n        \"open_issues\": 2,\n        \"watchers\": 0,\n        \"default_branch\": \"master\",\n        \"allow_squash_merge\": true,\n        \"allow_merge_commit\": true,\n        \"allow_rebase_merge\": true,\n        \"delete_branch_on_merge\": false\n      }\n    },\n    \"_links\": {\n      \"self\": {\n        \"href\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2\"\n      },\n      \"html\": {\n        \"href\": \"https://github.com/Codertocat/Hello-World/pull/2\"\n      },\n      \"issue\": {\n        \"href\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/2\"\n      },\n      \"comments\": {\n        \"href\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/2/comments\"\n      },\n      \"review_comments\": {\n        \"href\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2/comments\"\n      },\n      \"review_comment\": {\n        \"href\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/comments{/number}\"\n      },\n      \"commits\": {\n        \"href\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls/2/commits\"\n      },\n      \"statuses\": {\n        \"href\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/ec26c3e57ca3a959ca5aad62de7213c562f8c821\"\n      }\n    },\n    \"author_association\": \"OWNER\",\n    \"draft\": false,\n    \"merged\": false,\n    \"mergeable\": null,\n    \"rebaseable\": null,\n    \"mergeable_state\": \"unknown\",\n    \"merged_by\": null,\n    \"comments\": 0,\n    \"review_comments\": 0,\n    \"maintainer_can_modify\": false,\n    \"commits\": 1,\n    \"additions\": 1,\n    \"deletions\": 1,\n    \"changed_files\": 1\n  },\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:19:27Z\",\n    \"pushed_at\": \"2019-05-15T15:20:32Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": null,\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": true,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 2,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 2,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"Codertocat\",\n    \"id\": 21031067,\n    \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n    \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/Codertocat\",\n    \"html_url\": \"https://github.com/Codertocat\",\n    \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n    \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n    \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n    \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": false\n  }\n}",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "select event.metrics.pull_request.head.sha as hashid,\r\nevent.metrics.pull_request.state as pullreqstate, \r\nevent.metrics.pull_request.created_at as time,\r\nevent.metrics.pull_request.user.login as author, \r\nevent.metrics.pull_request.base.repo.owner.login as owner,\r\nevent.metrics.pull_request.body as message \r\nfrom test.git_json where event.repo == 'Github' and event.metrics.pull_request.head.sha !=''  SETTINGS describe_extend_object_types=1;"
    }
   ]
  },
  {
   "title": "Github Gollum Event",
   "type": "table",
   "description": "{\n  \"pages\": [\n    {\n      \"page_name\": \"Home\",\n      \"title\": \"Home\",\n      \"summary\": null,\n      \"action\": \"edited\",\n      \"sha\": \"6bf911d3801dd1ef957fc6ade5a8d96429e7fa39\",\n      \"html_url\": \"https://github.com/Codertocat/Hello-World/wiki/Home\"\n    }\n  ],\n  \"repository\": {\n    \"id\": 186853002,\n    \"node_id\": \"MDEwOlJlcG9zaXRvcnkxODY4NTMwMDI=\",\n    \"name\": \"Hello-World\",\n    \"full_name\": \"Codertocat/Hello-World\",\n    \"private\": false,\n    \"owner\": {\n      \"login\": \"Codertocat\",\n      \"id\": 21031067,\n      \"node_id\": \"MDQ6VXNlcjIxMDMxMDY3\",\n      \"avatar_url\": \"https://avatars1.githubusercontent.com/u/21031067?v=4\",\n      \"gravatar_id\": \"\",\n      \"url\": \"https://api.github.com/users/Codertocat\",\n      \"html_url\": \"https://github.com/Codertocat\",\n      \"followers_url\": \"https://api.github.com/users/Codertocat/followers\",\n      \"following_url\": \"https://api.github.com/users/Codertocat/following{/other_user}\",\n      \"gists_url\": \"https://api.github.com/users/Codertocat/gists{/gist_id}\",\n      \"starred_url\": \"https://api.github.com/users/Codertocat/starred{/owner}{/repo}\",\n      \"subscriptions_url\": \"https://api.github.com/users/Codertocat/subscriptions\",\n      \"organizations_url\": \"https://api.github.com/users/Codertocat/orgs\",\n      \"repos_url\": \"https://api.github.com/users/Codertocat/repos\",\n      \"events_url\": \"https://api.github.com/users/Codertocat/events{/privacy}\",\n      \"received_events_url\": \"https://api.github.com/users/Codertocat/received_events\",\n      \"type\": \"User\",\n      \"site_admin\": false\n    },\n    \"html_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"description\": null,\n    \"fork\": false,\n    \"url\": \"https://api.github.com/repos/Codertocat/Hello-World\",\n    \"forks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/forks\",\n    \"keys_url\": \"https://api.github.com/repos/Codertocat/Hello-World/keys{/key_id}\",\n    \"collaborators_url\": \"https://api.github.com/repos/Codertocat/Hello-World/collaborators{/collaborator}\",\n    \"teams_url\": \"https://api.github.com/repos/Codertocat/Hello-World/teams\",\n    \"hooks_url\": \"https://api.github.com/repos/Codertocat/Hello-World/hooks\",\n    \"issue_events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/events{/number}\",\n    \"events_url\": \"https://api.github.com/repos/Codertocat/Hello-World/events\",\n    \"assignees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/assignees{/user}\",\n    \"branches_url\": \"https://api.github.com/repos/Codertocat/Hello-World/branches{/branch}\",\n    \"tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/tags\",\n    \"blobs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/blobs{/sha}\",\n    \"git_tags_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/tags{/sha}\",\n    \"git_refs_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/refs{/sha}\",\n    \"trees_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/trees{/sha}\",\n    \"statuses_url\": \"https://api.github.com/repos/Codertocat/Hello-World/statuses/{sha}\",\n    \"languages_url\": \"https://api.github.com/repos/Codertocat/Hello-World/languages\",\n    \"stargazers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/stargazers\",\n    \"contributors_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contributors\",\n    \"subscribers_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscribers\",\n    \"subscription_url\": \"https://api.github.com/repos/Codertocat/Hello-World/subscription\",\n    \"commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/commits{/sha}\",\n    \"git_commits_url\": \"https://api.github.com/repos/Codertocat/Hello-World/git/commits{/sha}\",\n    \"comments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/comments{/number}\",\n    \"issue_comment_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues/comments{/number}\",\n    \"contents_url\": \"https://api.github.com/repos/Codertocat/Hello-World/contents/{+path}\",\n    \"compare_url\": \"https://api.github.com/repos/Codertocat/Hello-World/compare/{base}...{head}\",\n    \"merges_url\": \"https://api.github.com/repos/Codertocat/Hello-World/merges\",\n    \"archive_url\": \"https://api.github.com/repos/Codertocat/Hello-World/{archive_format}{/ref}\",\n    \"downloads_url\": \"https://api.github.com/repos/Codertocat/Hello-World/downloads\",\n    \"issues_url\": \"https://api.github.com/repos/Codertocat/Hello-World/issues{/number}\",\n    \"pulls_url\": \"https://api.github.com/repos/Codertocat/Hello-World/pulls{/number}\",\n    \"milestones_url\": \"https://api.github.com/repos/Codertocat/Hello-World/milestones{/number}\",\n    \"notifications_url\": \"https://api.github.com/repos/Codertocat/Hello-World/notifications{?since,all,participating}\",\n    \"labels_url\": \"https://api.github.com/repos/Codertocat/Hello-World/labels{/name}\",\n    \"releases_url\": \"https://api.github.com/repos/Codertocat/Hello-World/releases{/id}\",\n    \"deployments_url\": \"https://api.github.com/repos/Codertocat/Hello-World/deployments\",\n    \"created_at\": \"2019-05-15T15:19:25Z\",\n    \"updated_at\": \"2019-05-15T15:19:27Z\",\n    \"pushed_at\": \"2019-05-15T15:19:26Z\",\n    \"git_url\": \"git://github.com/Codertocat/Hello-World.git\",\n    \"ssh_url\": \"git@github.com:Codertocat/Hello-World.git\",\n    \"clone_url\": \"https://github.com/Codertocat/Hello-World.git\",\n    \"svn_url\": \"https://github.com/Codertocat/Hello-World\",\n    \"homepage\": null,\n    \"size\": 0,\n    \"stargazers_count\": 0,\n    \"watchers_count\": 0,\n    \"language\": null,\n    \"has_issues\": true,\n    \"has_projects\": true,\n    \"has_downloads\": true,\n    \"has_wiki\": true,\n    \"has_pages\": false,\n    \"forks_count\": 0,\n    \"mirror_url\": null,\n    \"archived\": false,\n    \"disabled\": false,\n    \"open_issues_count\": 0,\n    \"license\": null,\n    \"forks\": 0,\n    \"open_issues\": 0,\n    \"watchers\": 0,\n    \"default_branch\": \"master\"\n  },\n  \"sender\": {\n    \"login\": \"rachmari\",\n    \"id\": 9831992,\n    \"node_id\": \"MDQ6VXNlcjk4MzE5OTI=\",\n    \"avatar_url\": \"https://avatars2.githubusercontent.com/u/9831992?v=4\",\n    \"gravatar_id\": \"\",\n    \"url\": \"https://api.github.com/users/rachmari\",\n    \"html_url\": \"https://github.com/rachmari\",\n    \"followers_url\": \"https://api.github.com/users/rachmari/followers\",\n    \"following_url\": \"https://api.github.com/users/rachmari/following{/other_user}\",\n    \"gists_url\": \"https://api.github.com/users/rachmari/gists{/gist_id}\",\n    \"starred_url\": \"https://api.github.com/users/rachmari/starred{/owner}{/repo}\",\n    \"subscriptions_url\": \"https://api.github.com/users/rachmari/subscriptions\",\n    \"organizations_url\": \"https://api.github.com/users/rachmari/orgs\",\n    \"repos_url\": \"https://api.github.com/users/rachmari/repos\",\n    \"events_url\": \"https://api.github.com/users/rachmari/events{/privacy}\",\n    \"received_events_url\": \"https://api.github.com/users/rachmari/received_events\",\n    \"type\": \"User\",\n    \"site_admin\": true\n  }\n}",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "select event.metrics.pages.page_name[1] as WikiPage,\r\nevent.metrics.pages.title[1] as title,\r\nevent.metrics.repository.name as RepoName,\r\nevent.metrics.sender.login as Author\r\nfrom test.git_json where event.repo == 'Github' and event.metrics.pages.title[1] != '' SETTINGS describe_extend_object_types=1;"
    }
   ]
  }
 ]
}