version: "2"

services:
  nats:
    image: "nats:latest"
    entrypoint: "/nats-server -js"
    expose:
      - "4222"
    ports:
      - "8222:8222"
    hostname: nats-server
  git-agent:
    build:
      context: "./"
      dockerfile: ./agent.dockerfile
    links:
      - nats
    environment:
      - "NATS_ADDRESS=nats://nats:4222"
      - "NATS_TOKEN=UfmrJOYwYCCsgQvxvcfJ3BdI6c8WBbnD"
    depends_on:
      - nats
    ports:
      - "5001:5001"
