package events

import "github.com/kube-tarian/git-bridge/github"

var GithubEventTypesSlice = []github.Event{
	"check_run",
	"check_suite",
	"commit_comment",
	"create",
	"delete",
	"deploy_key",
	"deployment",
	"deployment_status",
	"fork",
	"gollum",
	"installation",
	"installation_repositories",
	"integration_installation",
	"integration_installation_repositories",
	"issue_comment",
	"issues",
	"label",
	"member",
	"membership",
	"milestone",
	"meta",
	"organization",
	"org_block",
	"page_build",
	"ping",
	"project_card",
	"project_column",
	"project",
	"public",
	"pull_request",
	"pull_request_review",
	"pull_request_review_comment",
	"push",
	"release",
	"repository",
	"repository_vulnerability_alert",
	"security_advisory",
	"status",
	"team",
	"team_add",
	"watch",
	"workflow_dispatch",
	"workflow_job",
	"workflow_run",
}
