package events

import "github.com/kube-tarian/git-bridge/github"

var GithubEventTypesSlice = []github.Event{
	"github.CheckRunEvent",
	"github.CheckSuiteEvent",
	"github.CommitCommentEvent",
	"github.CreateEvent",
	"github.DeleteEvent",
	"github.DeployKeyEvent",
	"github.DeploymentEvent",
	"github.DeploymentStatusEvent",
	"github.ForkEvent",
	"github.GollumEvent",
	"github.InstallationEvent",
	"github.InstallationRepositoriesEvent",
	"github.IntegrationInstallationEvent",
	"github.IntegrationInstallationRepositoriesEvent",
	"github.IssueCommentEvent",
	"github.IssuesEvent",
	"github.LabelEvent",
	"github.MemberEvent",
	"github.MembershipEvent",
	"github.MilestoneEvent",
	"github.MetaEvent",
	"github.OrganizationEvent",
	"github.OrgBlockEvent",
	"github.PageBuildEvent",
	"github.PingEvent",
	"github.ProjectCardEvent",
	"github.ProjectColumnEvent",
	"ProjectEvent",
	"github.PublicEvent",
	"github.PullRequestEvent",
	"github.PullRequestReviewEvent",
	"github.PullRequestReviewCommentEvent",
	"github.PushEvent",
	"github.ReleaseEvent",
	"github.RepositoryEvent",
	"github.RepositoryVulnerabilityAlertEvent",
	"github.SecurityAdvisoryEvent",
	"github.StatusEvent",
	"github.TeamEvent",
	"github.TeamAddEvent",
	"github.WatchEvent",
	"github.WorkflowDispatchEvent",
	"github.WorkflowJobEvent",
	"github.WorkflowRunEvent",
}
